v2fly:
    container_name: v2fly
    image: v2fly/v2fly-core:v4.34.0
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - /docker/v2fly:/etc/v2ray
      - /var/log/v2ray:/var/log/v2ray